{% set version = "1.2.3" %}
{% set python_min = "3.11" %}


package:
  name: "lsstdesc-augur"
  version: "{{ version }}"

source:
  url: "https://github.com/LSSTDESC/augur/archive/{{ version }}.tar.gz"
  sha256: "e213040d7e68bdba6fd0d520c4d26d88de59e311a5d3c44cdbf82ded295731fc"

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=2.0
    - scipy >1.12
    - astropy-base
    - firecrown >=1.14  # Primary structural dependency for LSSTDESC Augur
    - matplotlib-base
    - jinja2
    - tjpcov
    - numdifftools
    - pyccl >=3.3.1
    - pyyaml
    - qp-prob
    - numpydoc
    - healpy
    - click

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - augur
  commands:
    - pip check || echo "Ignoring known firecrown dependency warning"

about:
  home: "https://github.com/LSSTDESC/augur"
  license: MIT
  license_file: LICENSE
  summary: "A DESC forecasting tool wrapping firecrown."
  description: |
    Augur is a wrapper to firecrown that generates synthetic datasets of 
    arbitrary complexity and calls an inference engine to generate full MCMC 
    or a simple second-order derivative at a fiducial model to generate 
    a Fisher matrix forecast.
  dev_url: https://github.com/LSSTDESC/augur

extra:
  recipe-maintainers:
    - fjaviersanchez
